### ISSUE TITLE
How to preserve color command in \refCom's hyperlinks?

### ISSUE THREAD

**Issue by dbitouze** [T-F-S/tcolorbox#93]
I would like to preserve color command in `\refCom`'s hyperlinks (and the same for the keys, etc.).
It isn't the case, as pointed out by the following MCE, with `hyperref`'s `colorlinks` set to `true` or `false` (and `color hyperlink` seems to not being able to help).

Is there a workaround?

```latex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{documentation}

\tcbset{color command=red, color key=blue}

\hypersetup{colorlinks
  % =false
}

\begin{document}

\begin{docCommand}{foomakedocSubKey}{\marg{name}\marg{key path}}
\end{docCommand}

\begin{docKey}[foo]{footitle}{=\meta{text}}{no default, initially empty}
\end{docKey}

See \refCom{foomakedocSubKey} and \refKey{/foo/footitle}
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/72451073-ae3f0880-37bb-11ea-906a-107292aea6a4.png)

**Comment by samcarter** [comment]
are you maybe looking for `\tcbset{color hyperlink=red}`?

**Comment by dbitouze** [comment]
> are you maybe looking for `\tcbset{color hyperlink=red}`?

No, because the red color would apply to `\refCom` (okay) but to `\refKey` as well (not okay).

**Comment by samcarter** [comment]
This might break a few things, but you might be able to force separate colours like this:

```
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{documentation}

\tcbset{color command=red, color key=blue}

\hypersetup{colorlinks}

\makeatletter
\def\refCom{\hypersetup{linkcolor=\kvtcb@col@command}\tcb@ref@doc{com}}
\def\refKey{\hypersetup{linkcolor=\kvtcb@col@key}\tcb@ref@doc{key}}
\makeatother

\begin{document}

\begin{docCommand}{foomakedocSubKey}{\marg{name}\marg{key path}}
\end{docCommand}

\begin{docKey}[foo]{footitle}{=\meta{text}}{no default, initially empty}
\end{docKey}

See \refCom{foomakedocSubKey} and \refKey{/foo/footitle}
\end{document}
```

**Comment by muzimuzhi** [comment]
If what you want is to "keep the color of output linked text of \refCom unchanged no matter hyperref option `colorlinks` is set to true or false", then this is a hyperref-related question.

**Comment by dbitouze** [comment]
@T-F-S Shouldn't what @samcarter proposed be subject of a `tcolorbox` option?

**Comment by muzimuzhi** [comment]
```tex
\makeatletter
\def\refCom{\hypersetup{linkcolor=\kvtcb@col@command}\tcb@ref@doc{com}}
\def\refKey{\hypersetup{linkcolor=\kvtcb@col@key}\tcb@ref@doc{key}}
\makeatother

% normal
See \refCom{foomakedocSubKey} and \refKey{/foo/footitle}
% problematic, the color of \refKey leaks
\ref{com:foomakedocSubKey}
```
The current approach makes the range of `\hypersetup{linkcolor=...}` leaks. Here is a range-safe approach:
```tex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{documentation}

\tcbset{color command=red, color key=blue}
\hypersetup{colorlinks}

\makeatletter
% #1 = tcb link type
% #2 = hyp link color
% #3 = add page ref or not
% #4 = tcb ref name
\RenewDocumentCommand\tcb@ref@doc{ m o s m }{%
  \begingroup
  % change \@linkcolor locally, default is \kvtcb@colhyper
  \IfValueT{#2}{\hypersetup{linkcolor=#2}}%
  \hyperref[#1:#4]{\texttt{\ref*{#1:#4}}%
  \IfBooleanTF{#3}{}{%
    \ifnum\getpagerefnumber{#1:#4}=\thepage%
    \else%
      \textsuperscript{\ding{213}\,\kvtcb@text@pageshort\,\pageref*{#1:#4}}%
    \fi}}%
  \endgroup
}

%% all four usages of \tcb@ref@doc
\def\refCom{\tcb@ref@doc{com}[orange]} % set linkcolor to "orange"
\def\refEnv{\tcb@ref@doc{env}}
\def\refKey{\tcb@ref@doc{key}[]} % set linkcolor to default color (black)
\def\refPathOperation{\tcb@ref@doc{path}}
\makeatother

\begin{document}
\begin{docCommand}{foomakedocSubKey}{\marg{name}\marg{key path}}
\end{docCommand}

\begin{docKey}[foo]{footitle}{=\meta{text}}{no default, initially empty}
\end{docKey}


% test changed commands, with page ref
See \refCom{foomakedocSubKey} and \refKey{/foo/footitle}

\stepcounter{page}
% test changed commands, without page ref
See \refCom{foomakedocSubKey} and \refKey{/foo/footitle}

% test range is not leaked
\ref{com:foomakedocSubKey}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/72463615-9e9cdf80-380e-11ea-8753-f33d327d6b9c.png)

The redefinition of `\tcb@ref@doc` adds facility to set specific hyperref link color. It is even possible to set different color for link text and page ref. (Adding the facility of "sub-linkcolor" to hyperref would be the more elegant and general way.)

**Comment by muzimuzhi** [comment]
> (Adding the facility of "sub-linkcolor" to hyperref would be the more elegant and general way.)

A bit off-topic, here is a simple implementation of "sub-xxxcolor":
```tex
\documentclass{article}
\usepackage{xcolor}
\usepackage[colorlinks]{hyperref}

\makeatletter
% copied from `hyperref.sty`, line 3631--3639
\def\Hy@temp#1{%
  \expandafter\Hy@@temp\csname @#1color\endcsname{#1}%
}
\def\Hy@@temp#1#2#3{%
  \define@key{Hyp}{#2color}{%
    \HyColor@HyperrefColor{##1}#1%
  }%
  \def#1{#3}%
}

% define new hyp option "linksubcolor"
\Hy@temp{linksub}{red}

% set and restore hyp subcolor
\def\Hy@subcolor@set#1{%
  \@nameslet{Hy@color@temp}{@#1color}%
  \@nameslet{@#1color}{@#1subcolor}}
\def\Hy@subcolor@restore#1{%
  \@nameslet{@#1color}{Hy@color@temp}}

% helper cmd
\def\@nameslet#1#2{%
  \expandafter\let\csname#1\expandafter\endcsname\csname#2\endcsname}

% new ref cmd
\newcommand\newRef[1]{%
  \Hy@subcolor@set{link}%
  \autoref{#1}%
  \Hy@subcolor@restore{link}%
}
\makeatother

\begin{document}
\section{title}\label{key}
test \par

\def\test{normal ref: \autoref{key}, use subcolor: \newRef{key}\par}
\test

\hypersetup{linksubcolor=blue}
\test

\hypersetup{linksubcolor=orange!60!black}
\test
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/72465976-0c4b0a80-3813-11ea-96ca-e6ab6187f9dd.png)

This breaks some amount of (color) consistency, but may be helpful for some complicated (need sub types of link, cite, etc.) documents.

**Comment by dbitouze** [comment]
All of this is very nice, many thanks to both of you @samcarter and @muzimuzhi !

What would be nice is a way for the user to know the links are links, which is less easy to detect now the color links are not what they should be. AFAICS, e.g. `\hypersetup{pdfborderstyle={/S/U/W 1}}` doesn't work.

**Comment by muzimuzhi** [comment]
> What would be nice is a way for the user to know the links are links, which is less easy to detect now the color links are not what they should be. AFAICS, e.g. `\hypersetup{pdfborderstyle={/S/U/W 1}}` doesn't work.

This is a pure `hyperref` question, and is the more appropriate to ask.

The current implementation of `hyperref` sets options `pdfborder=0 0 0, pdfborderstyle=` at the beginning of `document` environment if option `colorlinks` is true.

**Comment by T-F-S** [comment]
I thought about if or how to include such features into the official package, but I tend to turn it down.

We would need a lot of new configuration keys for coloring the reference macros. For my part, I would not use different colors for document hyper links depending on what is linked. But that is pure taste. Other people may want to have

- colors for every `\refXXX` identical to the definition colors (like @dbitouze asked for)
- configurable colors for every `\refXXX` not identical to the definition colors
- colors to differ between `\refXXX` and `\refXXX*`
- change colors for the reference macro/key/etc, but not for the page reference
- ...

I think this list can be continued further.

But, I like the code of @muzimuzhi from https://github.com/T-F-S/tcolorbox/issues/93#issuecomment-574815163 very much which is a fine patch to customize for personal usage.

**Comment by muzimuzhi** [comment]
> I thought about if or how to include such features into the official package, but I tend to turn it down.
> ... ...
> I think this list can be continued further.

I agree. 

Setting different colors for user-configurable kinds of references or links looks like a general feature requirement, rather than some tcb-only features. And, to make the usage easier, kinds could be distinguished by prefixes of label names (like package `fancyref`) or label types (like package `cleveref` and `hyperref`).

**Comment by dbitouze** [comment]
@T-F-S 
>I think this list can be continued further.

Indeed, but my request sounds the most reasonable one, doesn't it? :smile:

**Comment by T-F-S** [comment]
@dbitouze 

> Indeed, but my request sounds the most reasonable one, doesn't it?

Therefore, your request takes the exclusive top position in the list :wink:

**Comment by muzimuzhi** [comment]
> And, to make the usage easier, kinds could be distinguished by prefixes of label names (like package `fancyref`) or label types (like package `cleveref` and `hyperref`).

@dbitouze I have implemented a patch to `hyperref` which uses different user-specified (sub-)linkcolors for different types of labels, if labels have the name scheme `<type>:<rest>` (for example, `\label{sec:intro}`).  Code and test are here https://github.com/muzimuzhi/latex-examples/commit/d44564772c1c361ff5135efcefc59769a65b0337 . Welcome to test.

Here is a test case for use with tcb's documentation library:
```tex
\documentclass{article}
\usepackage[documentation]{tcolorbox}

% ref: https://github.com/muzimuzhi/latex-examples/blob/master/utilities/hyperref-sublinkcolor.tex
\input{hyperref-sublinkcolor}
\hypersetup{colorlinks}

\begin{document}
% define labels
\begin{equation} 1 + 1\label{key} \end{equation}
\begin{docCommand}{cmd}{\marg{arg}} \end{docCommand}
\begin{docKey}[tcb]{key}{=\meta{value}}{} \end{docKey}
\begin{docEnvironment}{enumerate}{} \end{docEnvironment}

% ref labels
\def\test{
  base \autoref{key}; 
  cmd \refCom{cmd}, key \refKey{/tcb/key}, env \refEnv{enumerate}; 
  base \autoref{key}}

before: \par \test

\hypersetup{
  subcolorByLabelPrefix,
  sublinkcolor={com}{blue}, 
  sublinkcolor={env}{orange},
  sublinkcolor={key}{green!50!black}
}
after: \par \test
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/72717528-1ff9c680-3baf-11ea-8504-fc027084b2fc.png)

**Comment by T-F-S** [comment]
@muzimuzhi I think this new approach is quite clever and is applicable for many scenarios. Moreover, it is easy and comprehensible to use. I like it very much. :thumbsup:

**Comment by dbitouze** [comment]
Very nice indeed!

Just one thing. In the following MCE, where links are hidden (`hidelinks`), a colored text which is a link (thanks to `\href`) keeps its color. For e.g. a tcb colored command, its color is lost with `\refCom` link: too bad...

```latex
\documentclass{article}
\usepackage[documentation]{tcolorbox}

% ref: https://github.com/muzimuzhi/latex-examples/blob/master/utilities/hyperref-sublinkcolor.tex
\input{utilities/hyperref-sublinkcolor}

\hypersetup{hidelinks}
\tcbset{color command=blue}

\begin{document}
\begin{docCommand}{cmd}{\marg{arg}} \end{docCommand}

\begin{itemize}
\item \href{www.ctan.org}{\textcolor{red}{CTAN}}
\item cmd \refCom{cmd}
\end{itemize}
\end{document}
```

![test](https://user-images.githubusercontent.com/1032633/72790621-3ac34e00-3c36-11ea-8bb4-0564bc303c46.png)

**Comment by muzimuzhi** [comment]
> Just one thing. In the following MCE, where links are hidden (`hidelinks`), a colored text which is a link (thanks to `\href`) keeps its color.

@dbitouze 
This is again a hyperref-only issue, and your output is the expected behavior. See this example
```tex
\documentclass{article}
\usepackage{xcolor}
\usepackage{hyperref}
%\hypersetup{colorlinks}

\makeatletter
% equivalent to "\hypersetup{hidelinks}" but allowed to use inside document env
\def\HyHidelinks{
  \Hy@colorlinksfalse
  \Hy@ocgcolorlinksfalse
  \Hy@frenchlinksfalse
  \def\Hy@colorlink##1{\begingroup}%
  \def\Hy@endcolorlink{\endgroup}%
  \def\@pdfborder{0 0 0}%
  \let\@pdfborderstyle\ltx@empty
}
% equivalent to "\hypersetup{colorlinks}"
\def\HyColorlinks{
  \def\@pdfborder{0 0 0}%
  \let\@pdfborderstyle\@empty
  \def\Hy@colorlink##1{%
    \begingroup
    \HyColor@UseColor##1%
  }%
  \def\Hy@endcolorlink{\endgroup}%
}
\makeatother

\def\test{
  \begin{itemize}
    \item colored text: \textcolor{red}{CTAN}
    \item colored text inside href: \href{www.ctan.org}{C\textcolor{red}{T}AN}, \href{www.ctan.org}{C\textcolor{blue}{T}AN}
    \item normal ref: \ref{cmd}
  \end{itemize}
}

\begin{document}
\section{title}\label{cmd}

\section*{Normal}
\test

\section*{Set \texttt{colorlinks=true}}
\begingroup \HyColorlinks \test \endgroup

\section*{Set \texttt{hidelinks}}
\begingroup \HyHidelinks  \test \endgroup

\section*{Set \texttt{colorlinks=true, hidelinks}}
\begingroup \HyColorlinks\HyHidelinks  \test \endgroup
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/72897804-c1bf1600-3d5d-11ea-8940-39763d144fe8.png)

Setting `hidelinks` means hyperref will not add _extra_ style (color, border, etc.) to linked text. But if you manually specify styles to linked text, this style (bold or italic, color or boxed, etc.) is always kept.

**Comment by dbitouze** [comment]
Sorry for the delay.

And sorry but I still don't understand. In your last example "`colorlinks=true/false, hidelinks`", item "colored text inside href:", the red and blue colors of the "T" in "CTAN" are preserved. Why isn't it the case for `\refCom{cmd}` (which is more or less `\hyperref[label]{text}`):

```latex
\documentclass{article}
\usepackage[documentation]{tcolorbox}

% ref: https://github.com/muzimuzhi/latex-examples/blob/master/utilities/hyperref-sublinkcolor.tex
\input{utilities/hyperref-sublinkcolor}

\hypersetup{colorlinks=false,hidelinks}
\tcbset{color command=blue}

\begin{document}
\begin{docCommand}{cmd}{\marg{arg}} \end{docCommand}

\section{Section One}
\label{section-one}

\begin{itemize}
\item \hyperref[section-one]{\textcolor{blue}{Section 1}}
\item \textcolor{blue}{\hyperref[section-one]{Section 1}}
\item cmd \refCom{cmd}
\end{itemize}
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/73160257-c92d4900-40e8-11ea-8952-9ed84402283c.png)

**Comment by muzimuzhi** [comment]
> Why isn't it the case for `\refCom{cmd}` (which is more or less `\hyperref[label]{text}`)
@dbitouze 

1. Ignoring the page reference part, `\refCom{cmd}` is equivalent to
   ```tex
   \hyperref[com:cmd]{\texttt{\ref*{com:cmd}}
   ```
2. Hence
   - the output of `\refCom{...}` and `\hyeprref[]{<no color cmd>}` are alike, and
   - the output of `\textcolor{}{\refCom{}}`, `\textcolor{}{\hyperref[]{}}`, and `\hyperref[]{\textcolor{}{}}` are alike.

I am not sure if this explanation solves your doubts.

**Comment by dbitouze** [comment]
@muzimuzhi If I understand well, what I would need to preserve color command in hyperlinks of, say, `\refCom` (as asked in OP) is some new `tcolorbox` such as, say, `color refCom` that could be set as follows: `color refCom=color command` and the effect of which being `\refCom{⟨cmd⟩}` is equivalent to  something like:

```latex
\hyperref[com:⟨cmd⟩]{\texttt{\textcolor{⟨color refCom⟩}{\ref*{com:⟨cmd⟩}}}
```

**Comment by muzimuzhi** [comment]
@dbitouze 
Do you need to specify different color for (each pair of) tcb options like `color command=<color>` and `color refCom=<color>`? Or you just want a boolean option (for example, `\tcbset{color inherit=true/false}`) to control whether color of `\refCom` is inherited from hyperref's `linkcolor=<color>` or tcb's `color command=<color>`?

**Comment by dbitouze** [comment]
@muzimuzhi Indeed, I had in mind a boolean option such as `\tcbset{color inherit=true/false}`. But maybe some users may want to benefit from more granularity.

**Comment by muzimuzhi** [comment]
@dbitouze 
Based on the example given in https://github.com/T-F-S/tcolorbox/issues/93#issuecomment-574815163, the following (a-bit-lengthy) example provides four new tcb options, with syntax
```tex
\tcbset{
  color inherit         = <true or false>, % default true, init false
  color ref command     = <color>,         % value required, init \@linkcolor
  color ref environment = <color>,
  color ref key         = <color>,
  color ref path        = <color>
}
```

```tex
\documentclass{article}
\usepackage[documentation]{tcolorbox}
\tcbset{color command=red, color key=blue}

\hypersetup{colorlinks}

\makeatletter
\newif\iftcb@doc@colorinherit

% new boolean tcb option "color inherit"
% e.g., whether color of \refCom inherits from value of option "color command" or not
\tcbset{
  color inherit/.is if=tcb@doc@colorinherit,
  color inherit/.default=true,
  color inherit/.initial=false}

% #1 = key suffix
\def\tcb@tmpa#1{%
  \expandafter\tcb@tmpb\csname kvtcb@col@ref#1\endcsname{color ref #1}}
% #1 = stored in command
% #2 = key
\def\tcb@tmpb#1#2{%
  \tcbset{#2/.store in=#1, #2/.value required, #2=\@linkcolor}}

% new tcb options "color ref command/environment/key/path"
\tcb@tmpa{command}
\tcb@tmpa{environment}
\tcb@tmpa{key}
\tcb@tmpa{path}

% #1 = tcb ref type
% #2 = suffix of color-storing command
% #3 = add page ref or not
% #4 = tcb ref name
\RenewDocumentCommand\tcb@ref@doc{ m m s m }{%
  % if inherit, use color \kvtcb@col@<xxx>; otherwise use \kvtcb@col@ref<xxx>
  \iftcb@doc@colorinherit
    \expandafter\let\expandafter\tcb@ref@color\csname kvtcb@col@#2\endcsname
  \else
    \expandafter\let\expandafter\tcb@ref@color\csname kvtcb@col@ref#2\endcsname
  \fi
  % avoid using \color command if ref@color is the same as \@linkcolor
  \ifx\tcb@ref@color\@linkcolor
    \let\tcb@ref@color\relax
  \else
    \edef\tcb@ref@color{\noexpand\color{\tcb@ref@color}}%
  \fi
  \hyperref[#1:#4]{\tcb@ref@color\texttt{\ref*{#1:#4}}}%
  \IfBooleanTF{#3}{}{%
    \ifnum\getpagerefnumber{#1:#4}=\thepage%
    \else
      \textsuperscript{\tcb@ref@color\ding{213}\,\kvtcb@text@pageshort\,\pageref*{#1:#4}}%
    \fi
  }%
}

% redefine all four usages of \tcb@ref@doc
\def\refCom          {\tcb@ref@doc{com} {command}}
\def\refEnv          {\tcb@ref@doc{env} {environment}}
\def\refKey          {\tcb@ref@doc{key} {key}}
\def\refPathOperation{\tcb@ref@doc{path}{path}}
\makeatother

\begin{document}
\begin{docCommand}{foomakedocSubKey}{\marg{name}\marg{key path}}
\end{docCommand}

\begin{docKey}[foo]{footitle}{=\meta{text}}{no default, initially empty}
\end{docKey}


\def\test#1#2{
  \noindent With \texttt{#1}, colors of references are influenced by #2\par
  \tcbset{#1}
  % test changed commands, with page ref
  \setcounter{page}{1}
  See \refCom{foomakedocSubKey} and \refKey{/foo/footitle} \par
  \setcounter{page}{2}
  % test changed commands, without page ref
  See \refCom{foomakedocSubKey} and \refKey{/foo/footitle} \par
  % test scope is not leaked
  \ref{com:foomakedocSubKey}\par
  \medskip
}


\test{color inherit=false}{new options like \texttt{color ref command}}
\test{color inherit=true}{existing options like \texttt{color command}}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/73384697-b728f180-4306-11ea-9302-c3a4da90c8e3.png)

**Comment by muzimuzhi** [comment]
@dbitouze 
The example I gave yesterday, say https://github.com/T-F-S/tcolorbox/issues/93#issuecomment-579891634, did not take hyperref option `hidelinks` into consideration. I have updated that example and that leads to a new tcb option `color ignore hidelinks`.

There might need more effect on designing the user interface: which options would be added? how should options interact with each other? Relatively speaking, implementation is not _that_ hard.

**Comment by dbitouze** [comment]
That's very very nice, once again :smile: 

But, in some sense "hide links" is "ignore the colors of links" and hence "color ignore hidelinks" is "color ignore ignore the colors of links". This mental double "ignore" may be confusing. 

Moreover, if a user makes use of `hidelinks` option, I guess he would never want the case `color inherit=false` and `color ignore hidelinks=true` (your 3rd case when `hidelinks=true`): if he wants the links to be hidden, he probably wouldn't the tcolorbox (documentation)'s `\ref...` ones to not be hidden. Hence I'm not sure this `color ignore hidelinks` option is that useful.

**Comment by muzimuzhi** [comment]
@dbitouze

Sorry for the delay :(

> But, in some sense "hide links" is "ignore the colors of links" and hence "color ignore hidelinks" is "color ignore ignore the colors of links". This mental double "ignore" may be confusing.

Yes you are right. Does option name `color overwritten` better than `color ignore hidelinks`? Then `color overwritten=true` represents that the text color of `\refCom` is always the color set to `color command=<color>`, not the `linkcolor=<color>` from hyperref.

> Moreover, if a user makes use of `hidelinks` option, I guess he would never want the case `color inherit=false` and `color ignore hidelinks=true` (your 3rd case when `hidelinks=true`): if he wants the links to be hidden, he probably wouldn't the tcolorbox (documentation)'s `\ref...` ones to not be hidden. Hence I'm not sure this `color ignore hidelinks` option is that useful.

Firstly, I added `color ignore hidelinks` because by reading your comment (e.g., https://github.com/T-F-S/tcolorbox/issues/93#issuecomment-578644451), I thought you need something that can overwrite the effect of option `hidelinks`. If I wrongly understood your requirement, you can point out that. 

And, I should admit that there are bugs in my implementation in https://github.com/T-F-S/tcolorbox/issues/93#issuecomment-579891634. Should I insert `\color` by the true/false value of `\Hy@colorlinks[true|false]`? Does the value of `\Hy@ocgcolorlinks[true|false]` count?

Lastly, on purpose, I implemented the relationships of those five new tcb options as orthogonally as possible. They are even more orthogonal than those options originally provided by hyperref. Some, including `colorlinks` and `hidelinks`, of the hyperref options are preamble only. I.e., you can not use them inside `document` environment. The orthogonality was my personal preference and hence the corresponding examples shown all four cases, even the "useless" ones.
